/*
Estudantes:
Edson Dias Ferreira Júnior
Michel Oliveira Machado
Jhonatan Gratieri Simoni
Kluyvert Ananias Nunes
*/


USE LOCADORA_DE_VIDEO;

# UPDATES
# DATA PREVISTA DEVOLUÇÃO
UPDATE EMPRESTIMO SET DT_PREVDEV= DATE(DATE_ADD(DT_EMPRE, INTERVAL 3 DAY));


#ATUALIZAÇÃO DE SITUAÇÕES
#DEVOLVIDO
UPDATE EMPRESTIMO SET CD_SITU=1 WHERE DT_DEV<= DT_PREVDEV;

#ATRASADO
UPDATE EMPRESTIMO SET CD_SITU=2 WHERE DT_DEV IS NULL AND CURDATE()>DT_PREVDEV;

#EMPRESTADO
UPDATE EMPRESTIMO SET CD_SITU=3 WHERE DT_DEV IS NULL AND CURDATE()<=DT_PREVDEV;

#DEVOLVIDO COM ATRASO
UPDATE EMPRESTIMO SET CD_SITU=4 WHERE DT_DEV> DT_PREVDEV;


#ATUALIZAÇÕES DE STATUS
#PARA ENTUSIASTA
UPDATE CLIENTE C, EMPRESTIMO E, (SELECT C.NUM_CLIENTE
FROM CLIENTE C, EMPRESTIMO E
WHERE C.NUM_CLIENTE=E.NUM_CLIENTE AND C.CD_STATUS=1 AND E.CD_SITU=1 AND E.DT_DEV >= C.DT_NSTATUS
GROUP BY C.NUM_CLIENTE
HAVING COUNT(*)>=5 ) AS X
SET C.CD_STATUS=2, C.DT_NSTATUS="2000-05-14"
WHERE C.NUM_CLIENTE=X.NUM_CLIENTE;

#PARA VIP
UPDATE CLIENTE C,EMPRESTIMO E,(SELECT C.NUM_CLIENTE
FROM CLIENTE C, EMPRESTIMO E
WHERE C.NUM_CLIENTE=E.NUM_CLIENTE AND C.CD_STATUS=2 AND E.CD_SITU=1 AND E.DT_DEV >= C.DT_NSTATUS
GROUP BY C.NUM_CLIENTE
HAVING COUNT(*)>=10 ) AS X
SET C.CD_STATUS=3, C.DT_NSTATUS= "2001-05-14"
WHERE C.NUM_CLIENTE=X.NUM_CLIENTE;


#MUDANÇA STATUS DVD
#MUDAR DVD PARA LOCADO
UPDATE DVD D, (SELECT CD_DVD
FROM EMPRESTIMO E
WHERE E.CD_SITU=2 OR E.CD_SITU=3) AS X
SET D.SITU_ATUAL="LOCADO"
WHERE D.CD_DVD=X.CD_DVD;


# Relação de fitas emprestadas para determinado cliente, com o número do DVD, título do Filme, data de empréstimo e data prevista para devolução.

SELECT F.TITULO TITULO_DO_FILME, D.CD_DVD CÓDIGO_DO_DVD, F.CD_FILME CÓDIGO_DO_FILME, E.DT_EMPRE DATA_DO_EMPRÉSTIMO, E.DT_PREVDEV
DATA_PREVISTA_PARA_DEVOLUÇÃO
FROM EMPRESTIMO E, DVD D, FILME F
WHERE (E.CD_DVD=D.CD_DVD) AND (D.CD_FILME=F.CD_FILME) AND((E.CD_SITU=2) OR (E.CD_SITU=3) ) AND (E.NUM_CLIENTE=3);


# Relação de todas os DVDS de determinado título, mostrando o número do dvd e a situação do mesmo, se esta ou não locado. 

SELECT F.TITULO TÍTULO ,D.CD_DVD CÓDIGO_DO_DVD, D.SITU_ATUAL SITUAÇÃO
FROM DVD D, FILME F
WHERE D.CD_FILME=F.CD_FILME AND F.TITULO= "HOMEM DE FERRO";


# A data de devolução mais próximo de um DVD com um título desejado. 

SELECT E.CD_DVD CÓDIGO_DVD, MINIMO PRÓXIMA_DEVOLUÇÃO
FROM EMPRESTIMO E, DVD D, (SELECT D.CD_FILME, MIN(E.DT_PREVDEV) MINIMO
FROM EMPRESTIMO E, FILME F, DVD D
WHERE D.CD_FILME=F.CD_FILME AND D.CD_DVD=E.CD_DVD AND D.SITU_ATUAL="LOCADO" AND F.TITULO="RIDDICK 3" AND E.CD_SITU=3
GROUP BY D.CD_FILME) AS X
WHERE (E.CD_DVD=D.CD_DVD) AND (D.CD_FILME=X.CD_FILME) AND (E.DT_PREVDEV=MINIMO) AND (E.CD_SITU=3);


#Exibir todos os filmes de determinado ator.

SELECT F.CD_FILME, ATOR.NM_ARTIS, F.TITULO
FROM ATUA A, ATOR , FILME F
WHERE (A.CD_FILME=F.CD_FILME)AND (A.CD_ATOR=ATOR.CD_ATOR) AND ATOR.NM_ARTIS="ROBERT DOWNEY JR."
GROUP BY F.CD_FILME;


/*Exibir uma sugestão de filme1  para algum cliente: Exibir o título de filme mais recente entre as 
categorias que o cliente tem maior quantidade de locações e que no momento possui DVDs disponíveis para locação.*/

SELECT DISTINCT Z.TITULO, Z.ANO
FROM
(SELECT F.TITULO TITULO, F.ANO ANO
FROM FILME F, TEM T, DVD D, (SELECT T.CD_DESC MAIOR_CATEGORIA
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=3
GROUP BY T.CD_DESC
HAVING COUNT(T.CD_DESC)=(SELECT MAX(X.QUANTIDADE)
FROM (SELECT COUNT(T.CD_DESC) QUANTIDADE
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=3
GROUP BY T.CD_DESC) AS X )) AS Y
WHERE F.CD_FILME=T.CD_FILME AND D.CD_FILME=F.CD_FILME AND D.CD_FILME=T.CD_FILME AND D.SITU_ATUAL="DISPONIVEL" AND (T.CD_DESC=Y.MAIOR_CATEGORIA)) AS Z,
(SELECT MAX(F.ANO) ANO
FROM FILME F, TEM T, DVD D, (SELECT T.CD_DESC MAIOR_CATEGORIA
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=3
GROUP BY T.CD_DESC
HAVING COUNT(T.CD_DESC)=(SELECT MAX(X.QUANTIDADE)
FROM (SELECT COUNT(T.CD_DESC) QUANTIDADE
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=3
GROUP BY T.CD_DESC) AS X )) AS Y
WHERE F.CD_FILME=T.CD_FILME AND D.CD_FILME=F.CD_FILME AND D.CD_FILME=T.CD_FILME AND D.SITU_ATUAL="DISPONIVEL" AND T.CD_DESC=Y.MAIOR_CATEGORIA) AS W
WHERE Z.ANO=W.ANO;


/*Exibir uma sugestão de filme2 (aprimorada) para algum cliente: Exibir o título de filme mais 
recente entre as categorias que o cliente tem maior quantidade de locações e que possua como ator
estrelando os atores com maiores quantidade de filmes locados pelo cliente e que no momento possui
DVDs disponíveis para locação.*/

SELECT DISTINCT Z.TITULO, Z.ANO
FROM (
SELECT F.TITULO TITULO, F.ANO ANO
FROM FILME F, TEM T, DVD D, (SELECT T.CD_DESC MAIOR_CATEGORIA
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=2
GROUP BY T.CD_DESC
HAVING COUNT(T.CD_DESC)=(SELECT MAX(X.QUANTIDADE)
FROM (SELECT COUNT(T.CD_DESC) QUANTIDADE
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=2
GROUP BY T.CD_DESC) AS X )) AS Y
WHERE F.CD_FILME=T.CD_FILME AND D.CD_FILME=F.CD_FILME AND D.CD_FILME=T.CD_FILME AND D.SITU_ATUAL="DISPONIVEL" AND T.CD_DESC=Y.MAIOR_CATEGORIA) AS Z ,
(SELECT MAX(U.ANO) ANO
FROM (SELECT F.TITULO TITULO, F.ANO ANO, A.CD_ATOR ATOR
FROM FILME F, TEM T, DVD D, ATUA A, (SELECT T.CD_DESC MAIOR_CATEGORIA
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=2
GROUP BY T.CD_DESC
HAVING COUNT(T.CD_DESC)=(SELECT MAX(X.QUANTIDADE)
FROM (SELECT COUNT(T.CD_DESC) QUANTIDADE
FROM EMPRESTIMO E, DVD D, FILME F, TEM T
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=T.CD_FILME AND D.CD_FILME=T.CD_FILME AND E.NUM_CLIENTE=2
GROUP BY T.CD_DESC) AS X )) AS Y
WHERE F.CD_FILME=T.CD_FILME AND D.CD_FILME=F.CD_FILME AND D.CD_FILME=T.CD_FILME AND D.SITU_ATUAL="DISPONIVEL" AND T.CD_DESC=Y.MAIOR_CATEGORIA
AND A.CD_FILME=F.CD_FILME AND A.CD_FILME=T.CD_FILME AND A.CD_FILME=D.CD_FILME
HAVING ATOR= (SELECT MAX(A.CD_ATOR)
FROM EMPRESTIMO E, DVD D, FILME F, ATUA A
WHERE E.CD_DVD=D.CD_DVD AND D.CD_FILME=F.CD_FILME AND F.CD_FILME=A.CD_FILME AND A.CD_FILME=D.CD_FILME AND E.NUM_CLIENTE=2)) AS U) AS W
WHERE Z.ANO=W.ANO;
