

CREATE DATABASE IF NOT EXISTS LOCADORA_DE_VIDEO;

USE LOCADORA_DE_VIDEO;

DROP TABLE IF EXISTS ATUA;
DROP TABLE IF EXISTS TEM;
DROP TABLE IF EXISTS EMPRESTIMO;
DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS DVD;
DROP TABLE IF EXISTS FILME;
DROP TABLE IF EXISTS ATOR;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS STATUS_CLIENTE;
DROP TABLE IF EXISTS SITUACAO;


CREATE TABLE FILME(
CD_FILME INT AUTO_INCREMENT,
TITULO VARCHAR(40) NOT NULL,
ANO YEAR NOT NULL,
PRIMARY KEY(CD_FILME)
);


CREATE TABLE DVD(
CD_DVD INT AUTO_INCREMENT,
CD_FILME INT NOT NULL,
SITU_ATUAL VARCHAR(15) DEFAULT "DISPONIVEL",
FOREIGN KEY (CD_FILME) REFERENCES FILME(CD_FILME),
PRIMARY KEY(CD_DVD)
);


CREATE TABLE ATOR(
CD_ATOR INT AUTO_INCREMENT,
NM_ARTIS VARCHAR(40),
NM_REAL VARCHAR(40),
DT_NASC DATE,
PRIMARY KEY(CD_ATOR)
);


CREATE TABLE ATUA(
CD_FILME INT NOT NULL,
CD_ATOR INT,
PRIMARY KEY(CD_FILME,CD_ATOR),
FOREIGN KEY (CD_FILME) REFERENCES FILME(CD_FILME),
FOREIGN KEY (CD_ATOR) REFERENCES ATOR(CD_ATOR)
);


CREATE TABLE CATEGORIA(
CD_DESC INT AUTO_INCREMENT,
DESCR VARCHAR(15) NOT NULL,
PRIMARY KEY(CD_DESC)
);


CREATE TABLE TEM(
CD_DESC INT NOT NULL,
CD_FILME INT NOT NULL,
PRIMARY KEY(CD_FILME,CD_DESC),
FOREIGN KEY (CD_FILME) REFERENCES FILME(CD_FILME),
FOREIGN KEY (CD_DESC) REFERENCES CATEGORIA(CD_DESC)
);


CREATE TABLE STATUS_CLIENTE(
DESCR VARCHAR(15) NOT NULL,
CD_STATUS INT AUTO_INCREMENT,
PRIMARY KEY(CD_STATUS)
);


CREATE TABLE CLIENTE(
NUM_CLIENTE INT AUTO_INCREMENT,
NOME VARCHAR(15) NOT NULL,
SOBRENOME VARCHAR(15) NOT NULL,
ENDERECO VARCHAR(40) NOT NULL,
CD_STATUS INT DEFAULT 1,
DT_NSTATUS DATE,	#DATA QUE O CLIENTE MUDA DE CATEGORIA
FOREIGN KEY (CD_STATUS) REFERENCES STATUS_CLIENTE(CD_STATUS),
PRIMARY KEY(NUM_CLIENTE)
);


CREATE TABLE SITUACAO(
CD_SITU INT AUTO_INCREMENT,
DESCR VARCHAR(30) NOT NULL,
PRIMARY KEY(CD_SITU)
);


CREATE TABLE EMPRESTIMO(
CD_NF INT AUTO_INCREMENT,
NUM_CLIENTE INT NOT NULL,
CD_DVD INT NOT NULL,
DT_EMPRE DATE NOT NULL,
DT_PREVDEV DATE,
DT_DEV DATE,
CD_SITU INT,
UNIQUE KEY UNICO_EMP(CD_DVD,DT_EMPRE),
PRIMARY KEY(CD_NF),
FOREIGN KEY (CD_DVD) REFERENCES DVD(CD_DVD),
FOREIGN KEY (NUM_CLIENTE) REFERENCES CLIENTE(NUM_CLIENTE),
FOREIGN KEY (CD_SITU) REFERENCES SITUACAO(CD_SITU)
);


CREATE TABLE CONTATO(
NUM_CLIENTE INT NOT NULL,
TEL VARCHAR(20) NOT NULL,
FOREIGN KEY (NUM_CLIENTE) REFERENCES CLIENTE(NUM_CLIENTE),
PRIMARY KEY(TEL)
);


INSERT INTO FILME (TITULO, ANO) VALUES ("ROCK BALBOA", 2006);
INSERT INTO FILME (TITULO, ANO) VALUES ("VELOZES E FURIOSOS", 2001);
INSERT INTO FILME (TITULO, ANO) VALUES ("BLOODSHOT", 2020);
INSERT INTO FILME (TITULO, ANO) VALUES ("RIDDICK 3", 2013);
INSERT INTO FILME (TITULO, ANO) VALUES ("HOMEM DE FERRO", 2008);
INSERT INTO FILME (TITULO, ANO) VALUES ("SHERLOCK HOLMES: O JOGO DE SOMBRAS", 2011);
INSERT INTO FILME (TITULO, ANO) VALUES ("PATERSON", 2016);
INSERT INTO FILME (TITULO, ANO) VALUES ("ROGUE ONE", 2016);
INSERT INTO FILME (TITULO, ANO) VALUES ("JOGOS VORAZES", 2012);
INSERT INTO FILME (TITULO, ANO) VALUES ("RAMBO: ATÉ O FIM", 2019);

INSERT INTO DVD (CD_FILME) VALUES (5);
INSERT INTO DVD (CD_FILME) VALUES (5);
INSERT INTO DVD (CD_FILME) VALUES (6);
INSERT INTO DVD (CD_FILME) VALUES (5);
INSERT INTO DVD (CD_FILME) VALUES (1);
INSERT INTO DVD (CD_FILME) VALUES (2);
INSERT INTO DVD (CD_FILME) VALUES (3);
INSERT INTO DVD (CD_FILME) VALUES (4);
INSERT INTO DVD (CD_FILME) VALUES (7);
INSERT INTO DVD (CD_FILME) VALUES (8);
INSERT INTO DVD (CD_FILME) VALUES (8);
INSERT INTO DVD (CD_FILME) VALUES (3);
INSERT INTO DVD (CD_FILME) VALUES (9);
INSERT INTO DVD (CD_FILME) VALUES (10);

INSERT INTO ATOR (NM_ARTIS, NM_REAL, DT_NASC ) VALUES ("ROBERT DOWNEY JR.", "ROBERT JOHN DOWNEY JR.", "1965-04-04");
INSERT INTO ATOR (NM_ARTIS, NM_REAL, DT_NASC ) VALUES ("VIN DIESEL", "MARK SINCLAIR VICENT", "1967-07-18");
INSERT INTO ATOR (NM_ARTIS, NM_REAL, DT_NASC ) VALUES ("ADAM DRIVER", "ADAM DOUGLAS DRIVER", "1986-11-19");
INSERT INTO ATOR (NM_ARTIS, NM_REAL, DT_NASC ) VALUES ("JENNIFER LAWRENCE", "JENNIFER SHRADER LAWRENCE", "1990-08-15");
INSERT INTO ATOR (NM_ARTIS, NM_REAL, DT_NASC ) VALUES ("SYLVESTER STALLONE", "MICHAEL SYLVESTER GARDENZIO STALLONE", "1946-07-06");

INSERT INTO ATUA VALUES (1, 5);
INSERT INTO ATUA VALUES (2, 2);
INSERT INTO ATUA VALUES (3, 2);
INSERT INTO ATUA VALUES (4, 2);
INSERT INTO ATUA VALUES (5, 1);
INSERT INTO ATUA VALUES (6, 1);
INSERT INTO ATUA VALUES (7, 3);
INSERT INTO ATUA VALUES (8, 3);
INSERT INTO ATUA VALUES (9, 4);
INSERT INTO ATUA VALUES (10, 5);

INSERT INTO CATEGORIA (DESCR) VALUES ("AÇÃO");
INSERT INTO CATEGORIA (DESCR) VALUES ("ANIMAÇÃO");
INSERT INTO CATEGORIA (DESCR) VALUES ("AVENTURA");
INSERT INTO CATEGORIA (DESCR) VALUES ("COMÉDIA");
INSERT INTO CATEGORIA (DESCR) VALUES ("DRAMA");
INSERT INTO CATEGORIA (DESCR) VALUES ("FANTASIA");
INSERT INTO CATEGORIA (DESCR) VALUES ("ROMANCE");
INSERT INTO CATEGORIA (DESCR) VALUES ("SCIFI");
INSERT INTO CATEGORIA (DESCR) VALUES ("TERROR");

INSERT INTO TEM VALUES (1, 1);
INSERT INTO TEM VALUES (7, 1);
INSERT INTO TEM VALUES (3, 2);
INSERT INTO TEM VALUES (1, 3);
INSERT INTO TEM VALUES (3, 3);
INSERT INTO TEM VALUES (8, 3);
INSERT INTO TEM VALUES (1, 4);
INSERT INTO TEM VALUES (3, 4);
INSERT INTO TEM VALUES (8, 4);
INSERT INTO TEM VALUES (1, 5);
INSERT INTO TEM VALUES (3, 5);
INSERT INTO TEM VALUES (8, 5);
INSERT INTO TEM VALUES (1, 6);
INSERT INTO TEM VALUES (3, 6);
INSERT INTO TEM VALUES (4, 7);
INSERT INTO TEM VALUES (5, 7);
INSERT INTO TEM VALUES (7, 7);
INSERT INTO TEM VALUES (1, 8);
INSERT INTO TEM VALUES (3, 8);
INSERT INTO TEM VALUES (8, 8);
INSERT INTO TEM VALUES (1, 9);
INSERT INTO TEM VALUES (3, 9);
INSERT INTO TEM VALUES (6, 9);
INSERT INTO TEM VALUES (8, 9);
INSERT INTO TEM VALUES (1, 10);
INSERT INTO TEM VALUES (3, 10);
INSERT INTO TEM VALUES (5, 10);

INSERT INTO STATUS_CLIENTE (DESCR) VALUES("INICIANTE");
INSERT INTO STATUS_CLIENTE (DESCR) VALUES("ENTUSIASTA");
INSERT INTO STATUS_CLIENTE (DESCR) VALUES("VIP");

INSERT INTO CLIENTE (NOME, SOBRENOME,ENDERECO, DT_NSTATUS) VALUES ("JHONATAN","SIMONI","RODOVIA DO SOL, SN","2020-08-10");
INSERT INTO CLIENTE (NOME, SOBRENOME,ENDERECO, DT_NSTATUS) VALUES ("EDSON","MAGALHAES","RUA DA MARINHA, 012","2020-09-20");
INSERT INTO CLIENTE (NOME, SOBRENOME,ENDERECO, DT_NSTATUS) VALUES ("MICHEL","MACHADO","OLARIA, 153","2020-10-20");

INSERT INTO CONTATO VALUES (1,"(27)997979898");
INSERT INTO CONTATO VALUES (2,"(27)996969595");
INSERT INTO CONTATO VALUES (3,"(27)991916969");

INSERT INTO SITUACAO (DESCR) VALUES ("DEVOLVIDO");
INSERT INTO SITUACAO (DESCR) VALUES ("ATRASADO");
INSERT INTO SITUACAO (DESCR) VALUES ("EMPRESTADO");
INSERT INTO SITUACAO (DESCR) VALUES ("DEVOLVIDO COM ATRASO");

INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2021-12-10", "2021-12-11", 1, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2021-12-12", "2021-12-20", 1, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2021-12-21", "2021-12-22", 1, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-12", "2022-01-14", 6, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-14", "2022-01-15", 9, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-15", "2022-01-16", 9, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-16", "2022-01-20", 7, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-17", "2022-01-18", 5, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-18", "2022-01-19", 8, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-20", "2022-01-22", 9, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-01", "2022-02-23", 1, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-03", "2022-02-24", 11, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-04", "2022-02-25", 10, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-06", "2022-02-28", 5, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-07", "2022-02-27", 7, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-08", "2022-02-20", 1, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, DT_DEV, CD_DVD, NUM_CLIENTE) VALUES ("2022-02-10", "2022-02-21", 2, 1);

INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-20", 10, 3);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-20", 7, 3);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-20", 5, 3);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-21", 1, 2);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-21", 11, 3);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-21", 8, 3);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-22", 8, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-23", 9, 1);
INSERT INTO EMPRESTIMO (DT_EMPRE, CD_DVD, NUM_CLIENTE) VALUES ("2022-01-24", 10, 1);


